### ISSUE TITLE
Where should this code reside?

### ISSUE THREAD

**Issue by cidrbl0ck** [brandonganem/rsyslog_configs#2]
First off apologies for posting this here as an Issue.. I tried finding another contact path and could not.

I'm just wanting to verify where is the intended home for this code? 
Part of rsyslog.conf, 50-default.conf or it's own conf file under /etc/rsyslog.d?

Thanks!!

**Comment by brandonganem** [comment]
The way these were written they would be `rsyslog.conf`. I'd recommend breaking things down into their own files under `rsyslog.d` though. Keep in mind I haven't used or tested this stuff in years, so who knows how well it works.

**Comment by cidrbl0ck** [comment]
Thanks Brandon, I thought so (about rsyslog.conf) but appreciate the clarification. The lack of information, and more importantly examples, in the wild of configuring Rsyslog for multiple ports and multiple rulesets with or without filters forced me to ask. You have a prime working example here. Thanks
